init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd BuildApp
  - cmd: build.cmd UnitTests
  - cmd: build.cmd IntegrationTests -ev DDDESIGNKIT_OAUTHTOKEN "%DDDESIGNKIT_OAUTHTOKEN%"
test: off
artifacts:
  - path: packaging\*.nupkg